### ISSUE TITLE
Google being detected as a blocked/malicious site by extension?

### ISSUE THREAD

**Issue by dynalar** [phantom/blocklist#941] opened 2024-02-20 16:27 UTC
![image](https://github.com/phantom/blocklist/assets/7396952/3f5b397d-692a-4a54-a0ea-bf49cb952efd)

Basically the post, whenever I use the Brave search bar (Google is my default search engine), it redirects to this message on screen.

**Comment by drewtunney** [comment] 2024-02-20 16:42
duplicate of #942 942

**Closed** 2024-02-21 09:39 UTC
