### ISSUE TITLE
Google.com is blocked..

### ISSUE THREAD

**Issue by JackCrispy** [phantom/blocklist#940] opened 2024-02-20 16:26 UTC
![image](https://github.com/phantom/blocklist/assets/34707863/444785b9-7d65-4021-bdc7-67382a77d5d7)

Hey guys, here's the issue. Uninstalling phantom now. Thanks!

**Comment by JakkuSakura** [comment] 2024-02-20 16:27
Fuck phantom. Same issue

**Comment by hirakujira** [comment] 2024-02-20 16:27
This is hilarious.

**Comment by JackCrispy** [comment] 2024-02-20 16:28
Yesterday it was cloudflare, now google. shame

**Comment by drewtunney** [comment] 2024-02-20 16:43
duplicate of #942

**Comment by JackCrispy** [comment] 2024-02-20 16:48
> duplicate of #942

how can this be a duplicate if 942 is 2 numbers after 940.

**Closed** 2024-02-21 09:39 UTC
